### ISSUE TITLE
How to have separate jvm benchmarks sourcesets and extending jvmMain

### ISSUE THREAD

**Issue by elect86** [Kotlin/kotlinx-benchmark#111]
As titled, I'm trying to have a jvm source set for benchmarking (just the jvm for the moment) and I'd like to have it extending `jvmMain` source and dependencies, so that I don't have to re-implement expected classes just for this additional source set

This is my setup so far:

```
plugins {
    kotlin("multiplatform") version embeddedKotlinVersion
    id("org.jetbrains.kotlinx.benchmark") version "0.4.3"
}
kotlin {
    jvm {
        compilations {
            val main by getting
            val jvmBench by creating {
                defaultSourceSet {
                    dependencies {
                        implementation(main.compileDependencyFiles + main.output.classesDirs)
                    }
                }
            }
        }
    }
    sourceSets {
        val commonMain by getting {
            dependencies {
                implementation("org.jetbrains.kotlinx:kotlinx-benchmark-runtime:0.4.3")
            }
        }
        val jvmMain by getting
        val jvmBench by creating {
            dependsOn(jvmMain)
        }
    }
}
benchmark {
    targets {
        register("jvmBench")
    }
}
```

At the sync, I get the following:

> * Exception is:
org.gradle.api.internal.tasks.DefaultTaskContainer$TaskCreationException: Could not create task ':compileJvmBenchKotlinJvm'
        ...
	at Build_gradle.<init>(build.gradle.kts:85)
	at Program.execute(Unknown Source)
	at Program.execute(Unknown Source)
	...
	at org.jetbrains.plugins.gradle.model.ProjectImportAction.execute(ProjectImportAction.java:126)
	at org.jetbrains.plugins.gradle.model.ProjectImportAction.execute(ProjectImportAction.java:43)
Caused by: org.gradle.api.UnknownDomainObjectException: SourceSet with name 'jvmBench' not found.
        ..
	at org.jetbrains.kotlin.gradle.plugin.mpp.KotlinJvmCompilation.getCompileJavaTaskProvider(KotlinJvmCompilation.kt:38)
	at org.jetbrains.kotlin.gradle.tasks.KotlinCompile$Configurator.configure(Tasks.kt:574)
	at org.jetbrains.kotlin.gradle.tasks.KotlinTasksProvider$registerKotlinJVMTask$1.execute(TasksProvider.kt:110)
	at org.jetbrains.kotlin.gradle.tasks.KotlinTasksProvider$registerKotlinJVMTask$1.execute(TasksProvider.kt:108)
	
What am I missing?

**Comment by kyay10** [comment]
Workaround (based on other solutions online) is:
```
kotlin {
    jvm {
        compilations {
            all { kotlinOptions.jvmTarget = "1.8" }

            val main by getting
            val bench by creating { associateWith(main) }

            benchmark.targets.add(
                    KotlinJvmBenchmarkTarget(
                            benchmark,
                            bench.defaultSourceSet.name,
                            bench,
                    )
            )
        }
    }
    // No need for sourceset config for jvmBench because `associateWith` makes it depend on jvmMain's sources
}
// Also no need for registering benchmark target since that is done above
```
Perhaps benchmark.targets.register should be aware of jvm sourcesets?
