### ISSUE TITLE
Support Gradle Project Isolation

### ISSUE THREAD

**Issue by dmitry-stakhov** [Kotlin/kotlinx-benchmark#258]
[Here](https://github.com/Kotlin/kotlinx-benchmark/blob/ce7bca66a9cb3dfb8e5ad842d553f62e61e23734/plugin/main/src/kotlinx/benchmark/gradle/BenchmarkConfiguration.kt#L73) we use `findProperty` function that looks to another Gradle Projects and break the Gradle sync with enabled Project isolation feature:

```
property benchmarks_jmh_version of :benchmarks
Project :benchmarks cannot dynamically look up a property in the parent project :
```

Possible solution can be to use `providers.gradleProperty("benchmarks_jmh_version").orNull` instead.

**Comment by fzhinkin** [comment]
@deep4nsh, you can take the issue.

**Comment by deep4nsh** [comment]
Thanks.

**Comment by deep4nsh** [comment]
I forked the repo and commites the solution. @fzhinkin @dmitry-stakhov

**Comment by fzhinkin** [comment]
@deep4nsh please open a pull request once you are ready to contribute the change.

**Comment by deep4nsh** [comment]
yes done

**Comment by liutikas** [comment]
Turns out this is not yet fully fixed. There is one more call to findProperty

```
org.gradle.api.InvalidUserCodeException: Project ':tracing:tracing-wire' cannot dynamically look up a property in the parent project ':tracing'
	at org.gradle.api.internal.project.DefaultProject.findProperty(DefaultProject.java:1166)
	at kotlinx.benchmark.gradle.UtilsKt.checkJmhVersion(Utils.kt:291)
	at kotlinx.benchmark.gradle.JvmMultiplatformTasksKt.configureMultiplatformJvmCompilation(JvmMultiplatformTasks.kt:29)
	at kotlinx.benchmark.gradle.JvmMultiplatformTasksKt.processJvmCompilation(JvmMultiplatformTasks.kt:11)
	at kotlinx.benchmark.gradle.BenchmarksPlugin$processConfigurations$1.invoke(BenchmarksPlugin.kt:117)
	at kotlinx.benchmark.gradle.BenchmarksPlugin$processConfigurations$1.invoke(BenchmarksPlugin.kt:114)
	at kotlinx.benchmark.gradle.BenchmarksPlugin.processConfigurations$lambda$4(BenchmarksPlugin.kt:114)
	at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:186)
	at kotlinx.benchmark.gradle.BenchmarksPlugin.processConfigurations(BenchmarksPlugin.kt:114)
	at kotlinx.benchmark.gradle.BenchmarksPlugin.access$processConfigurations(BenchmarksPlugin.kt:14)
	at kotlinx.benchmark.gradle.BenchmarksPlugin$apply$1$2.invoke(BenchmarksPlugin.kt:102)
	at kotlinx.benchmark.gradle.BenchmarksPlugin$apply$1$2.invoke(BenchmarksPlugin.kt:86)
	at kotlinx.benchmark.gradle.BenchmarksPlugin.apply$lambda$2$lambda$1(BenchmarksPlugin.kt:86)
```
